export enum cartActionName {
  ADD_TO_CART = "ADD_TO_CART",
  INCREMENT_ITEM_COUNT_FROM_CART = "INCREMENT_ITEM_COUNT_FROM_CART",
  DECREMENT_ITEM_COUNT_FROM_CART = "DECREMENT_ITEM_COUNT_FROM_CART",
  REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART",
}
